// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class Category
{
    public string Id { get; set; }

    public string ParentCategoryId { get; set; }

    public string Name { get; set; }

    public string NameId { get; set; }

    public string Photo { get; set; }

    public int? SequanceManager { get; set; }

    public int? SequanceUser { get; set; }

    public string Description { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual ICollection<CategoryLanguage> CategoryLanguages { get; set; } = new List<CategoryLanguage>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual Category ParentCategory { get; set; }
}