// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class Item
{
    public string Id { get; set; }

    public string CategoryId { get; set; }

    public string Name { get; set; }

    public string NameId { get; set; }

    public decimal Price { get; set; }

    public decimal Cost { get; set; }

    public string Photo { get; set; }

    public int? SequanceManager { get; set; }

    public int? SequanceUser { get; set; }

    public string Description { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public bool IsPromo { get; set; }

    public int? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public virtual Category Category { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<ItemLanguage> ItemLanguages { get; set; } = new List<ItemLanguage>();

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}