// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class Language
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Photo { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public bool IsDefault { get; set; }

    public virtual ICollection<CategoryLanguage> CategoryLanguages { get; set; } = new List<CategoryLanguage>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<DietLanguage> DietLanguages { get; set; } = new List<DietLanguage>();

    public virtual ICollection<ItemLanguage> ItemLanguages { get; set; } = new List<ItemLanguage>();

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual ICollection<LocationLanguage> LocationLanguages { get; set; } = new List<LocationLanguage>();

    public virtual ICollection<MapLanguage> MapLanguages { get; set; } = new List<MapLanguage>();

    public virtual ICollection<MenuLanguage> MenuLanguages { get; set; } = new List<MenuLanguage>();

    public virtual ICollection<OrderStatusLanguage> OrderStatusLanguages { get; set; } = new List<OrderStatusLanguage>();

    public virtual ICollection<RestorantTableLanguage> RestorantTableLanguages { get; set; } = new List<RestorantTableLanguage>();
}