// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class OrderDetail
{
    public string Id { get; set; }

    public string OrderId { get; set; }

    public string OrderStatusId { get; set; }

    public string ItemId { get; set; }

    public int Amount { get; set; }

    public decimal Cost { get; set; }

    public decimal Price { get; set; }

    public int? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Item Item { get; set; }

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderDetailTracking> OrderDetailTrackings { get; set; } = new List<OrderDetailTracking>();

    public virtual OrderStatus OrderStatus { get; set; }
}