// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class Order
{
    public string Id { get; set; }

    public string OrderStatusId { get; set; }

    public string OrderLanguageId { get; set; }

    public string PrintLanguageId { get; set; }

    public string Name { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public string ReceivedBy { get; set; }

    public int? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime? PrintDate { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderTracking> OrderTrackings { get; set; } = new List<OrderTracking>();

    public virtual User ReceivedByNavigation { get; set; }
}