// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class OrderStatus
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Photo { get; set; }

    public string Description { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual ICollection<OrderDetailTracking> OrderDetailTrackings { get; set; } = new List<OrderDetailTracking>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderStatusLanguage> OrderStatusLanguages { get; set; } = new List<OrderStatusLanguage>();

    public virtual ICollection<OrderTracking> OrderTrackings { get; set; } = new List<OrderTracking>();
}