// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class OrderTracking
{
    public string Id { get; set; }

    public string OrderId { get; set; }

    public string StatusId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderStatus Status { get; set; }
}