// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class RestorantTable
{
    public string Id { get; set; }

    public string MapId { get; set; }

    public string Name { get; set; }

    public string Photo { get; set; }

    public string Description { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public int PhotoLocationX { get; set; }

    public int PhotoLocationY { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual Map Map { get; set; }

    public virtual ICollection<RestorantTableLanguage> RestorantTableLanguages { get; set; } = new List<RestorantTableLanguage>();
}