// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dama.POS.DAL.Models;

public partial class User
{
    public string Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Photo { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual ICollection<Category> CategoryCreatedByNavigations { get; set; } = new List<Category>();

    public virtual ICollection<CategoryLanguage> CategoryLanguageCreatedByNavigations { get; set; } = new List<CategoryLanguage>();

    public virtual ICollection<CategoryLanguage> CategoryLanguageLastModifiedByNavigations { get; set; } = new List<CategoryLanguage>();

    public virtual ICollection<Category> CategoryLastModifiedByNavigations { get; set; } = new List<Category>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Diet> DietCreatedByNavigations { get; set; } = new List<Diet>();

    public virtual ICollection<DietLanguage> DietLanguageCreatedByNavigations { get; set; } = new List<DietLanguage>();

    public virtual ICollection<DietLanguage> DietLanguageLastModifiedByNavigations { get; set; } = new List<DietLanguage>();

    public virtual ICollection<Diet> DietLastModifiedByNavigations { get; set; } = new List<Diet>();

    public virtual ICollection<User> InverseCreatedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<User> InverseLastModifiedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<Item> ItemCreatedByNavigations { get; set; } = new List<Item>();

    public virtual ICollection<ItemLanguage> ItemLanguageCreatedByNavigations { get; set; } = new List<ItemLanguage>();

    public virtual ICollection<ItemLanguage> ItemLanguageLastModifiedByNavigations { get; set; } = new List<ItemLanguage>();

    public virtual ICollection<Item> ItemLastModifiedByNavigations { get; set; } = new List<Item>();

    public virtual ICollection<Language> LanguageCreatedByNavigations { get; set; } = new List<Language>();

    public virtual ICollection<Language> LanguageLastModifiedByNavigations { get; set; } = new List<Language>();

    public virtual User LastModifiedByNavigation { get; set; }

    public virtual ICollection<Location> LocationCreatedByNavigations { get; set; } = new List<Location>();

    public virtual ICollection<LocationLanguage> LocationLanguageCreatedByNavigations { get; set; } = new List<LocationLanguage>();

    public virtual ICollection<LocationLanguage> LocationLanguageLastModifiedByNavigations { get; set; } = new List<LocationLanguage>();

    public virtual ICollection<Location> LocationLastModifiedByNavigations { get; set; } = new List<Location>();

    public virtual ICollection<Map> MapCreatedByNavigations { get; set; } = new List<Map>();

    public virtual ICollection<MapLanguage> MapLanguageCreatedByNavigations { get; set; } = new List<MapLanguage>();

    public virtual ICollection<MapLanguage> MapLanguageLastModifiedByNavigations { get; set; } = new List<MapLanguage>();

    public virtual ICollection<Map> MapLastModifiedByNavigations { get; set; } = new List<Map>();

    public virtual ICollection<Menu> MenuCreatedByNavigations { get; set; } = new List<Menu>();

    public virtual ICollection<MenuLanguage> MenuLanguageCreatedByNavigations { get; set; } = new List<MenuLanguage>();

    public virtual ICollection<MenuLanguage> MenuLanguageLastModifiedByNavigations { get; set; } = new List<MenuLanguage>();

    public virtual ICollection<Menu> MenuLastModifiedByNavigations { get; set; } = new List<Menu>();

    public virtual ICollection<Order> OrderCreatedByNavigations { get; set; } = new List<Order>();

    public virtual ICollection<OrderDetail> OrderDetailCreatedByNavigations { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderDetail> OrderDetailLastModifiedByNavigations { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderDetailTracking> OrderDetailTrackings { get; set; } = new List<OrderDetailTracking>();

    public virtual ICollection<Order> OrderLastModifiedByNavigations { get; set; } = new List<Order>();

    public virtual ICollection<Order> OrderReceivedByNavigations { get; set; } = new List<Order>();

    public virtual ICollection<OrderStatus> OrderStatusCreatedByNavigations { get; set; } = new List<OrderStatus>();

    public virtual ICollection<OrderStatusLanguage> OrderStatusLanguageCreatedByNavigations { get; set; } = new List<OrderStatusLanguage>();

    public virtual ICollection<OrderStatusLanguage> OrderStatusLanguageLastModifiedByNavigations { get; set; } = new List<OrderStatusLanguage>();

    public virtual ICollection<OrderStatus> OrderStatusLastModifiedByNavigations { get; set; } = new List<OrderStatus>();

    public virtual ICollection<OrderTracking> OrderTrackings { get; set; } = new List<OrderTracking>();

    public virtual ICollection<RestorantTable> RestorantTableCreatedByNavigations { get; set; } = new List<RestorantTable>();

    public virtual ICollection<RestorantTableLanguage> RestorantTableLanguageCreatedByNavigations { get; set; } = new List<RestorantTableLanguage>();

    public virtual ICollection<RestorantTableLanguage> RestorantTableLanguageLastModifiedByNavigations { get; set; } = new List<RestorantTableLanguage>();

    public virtual ICollection<RestorantTable> RestorantTableLastModifiedByNavigations { get; set; } = new List<RestorantTable>();
}